### ISSUE TITLE
`color` flag in composite_layers function

### ISSUE THREAD

**Issue by naoto0804** [preddy5/DiffCompositing#1]
Thank you for making this wonderful repo publicly available! 
Could you elaborate a bit more on what is [color](https://github.com/preddy5/DiffCompositing/blob/master/DC/compositing.py#L30-L33) for?

**Comment by preddy5** [comment]
@naoto0804  thank you, the color parameter is used if we optimize rgb color of each element. This part is necessary to generate experiments from fig8 of the paper(http://geometry.cs.ucl.ac.uk/projects/2020/diffcompositing/paper_docs/paper.pdf)

**Comment by naoto0804** [comment]
Gotcha, thanks!
