### ISSUE TITLE
Final discretization

### ISSUE THREAD

**Issue by marzia-riso** [preddy5/DiffCompositing#2]
Hi,
Thank you for your contribution! I tested your code on the orange pattern example and I saw that the continuous result is saved.
Is it possible to save the discretized result too?  Unfortunately no input option seems to do that.
Thank you in advance for your answer!

**Comment by preddy5** [comment]
Hey @marzia-riso 
These are the two main functions I used for creating the final image
https://gist.github.com/preddy5/810e2eb222f92f17db416686eeea616a  This is the final file that uses the functions for creating the images, I wrote the code a few days before the deadline, I apologize for how shabby it is, I hope it is useful
https://gist.github.com/preddy5/e1f1654e87bab92a2f0d8a14d3a106ae

**Comment by marzia-riso** [comment]
Thank you so much for your answer!  It only took a few minutes to make the code work perfectly!

**Comment by preddy5** [comment]
@marzia-riso I am glad to hear that :)
